# Generated by Django 4.0.6 on 2022-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SALES', 'Sales'), ('SUPPORT', 'Support'), ('MANAGEMENT', 'Management')], default='Null', max_length=10),
        ),
    ]
