# Generated by Django 4.0.6 on 2022-08-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('first_name',), 'verbose_name': 'Utilisateurs', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
